server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_planner?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_woogi
    password: 1234
  jwt:
    secret: "A7dk@Z!pP9rXqLm3#sWvTjE2bNcY$uKd"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
