server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://219.255.15.170:3307/planner_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwer1234

  jwt:
    secret: A7dk@Z!pP9rXqLm3#sWvTjE2bNcY$uKd

  redis:
    host: 219.255.15.170
    port: 6383
    timeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
