server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/planner_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: maria

  jwt:
    secret: "A7dk@Z!pP9rXqLm3#sWvTjE2bNcY$uKd"

  redis:
    host: 219.255.15.170
    port: 6383
    timeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
