server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/planner_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: test

  jwt:
    secret: A7dk@Z!pP9rXqLm3#sWvTjE2bNcY$uKd

  redis:
    host: redis
    port: 6379
    timeout: 60000

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
